#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import shutil
from OOHw.interface.InterfaceFactory import InterfaceFactory
from OOHw.files.BINWriter import BINWriter
import powerSupply as pW
import coordinatesFile as cF
import stages

def acquireData( tektronix, numAcquisitions, averageNumber, filename ):
  tektronix.obtainPreamble()
  binwriter = BINWriter( filename )
  binwriter.header = tektronix.preamble
  for i in range( 1, numAcquisitions + 1 ):
    tektronix.controlAcquisition( "RUN" )
    waveform, points, bytesPoint = tektronix.readWaveformBIN( averageNumber )
    binwriter.addData( waveform )
  binwriter.bytesPerPoint( bytesPoint )
  binwriter.pointsPerMeasurement( points )
  binwriter.writeData()
  binwriter.close()

def getElectronicNoiseSignal( s, sensors, args, tektronix ):
  coord = list( sensors[ args.subparser ] )
  coord[ 1 ] += 5000
  stages.sendtoCoordinates( s, coord )
  print "\nAcquiring electronic noise"
  acquireData( tektronix, 1, args.average_number, "electronicNoise.bin" )
  stages.sendtoCoordinates( s, sensors[ args.subparser ] )

def findOptimumPosition( sensors, tektronix, args ):
  data = []
  axes = [ "x", "y", "z" ]
  if args.size in [ "Ref", "Small" ]:
    # Small diodes measure 1.3mm wide. Reference 1.8mm wide.
    rangesteps = { "x" : [ -50, 50, 5 ], "y" : [ -50, 50, 5 ], "z" : [ -9000, 15000, 100 ] }
  else:
    # Big diodes measure 3mm wide.
    rangesteps = { "x" : [ -2500, 2500, 100 ], "y" : [ -2500, 2500, 100 ], "z" : [ -13000, 4000, 300 ] }
  center = sensors[ args.subparser ]
  rangoX = range( rangesteps[ "x" ][ 0 ], rangesteps[ "x" ][ 1 ], rangesteps[ "x" ][ 2 ] )
  rangoY = range( rangesteps[ "y" ][ 0 ], rangesteps[ "y" ][ 1 ], rangesteps[ "y" ][ 2 ] )
  s = stages.open_socket()
  for i in rangoX:
    data.append( [] )
    for j in rangoY:
      coordinates = center[ : ]
      coordinates[ 0 ] += i
      coordinates[ 1 ] += j
      print "\nAcquiring in (x,y): (%d/%d, %d/%d)" % ( rangoX.index( i ) + 1, len( rangoX ), rangoY.index( j ) + 1, len( rangoY ) )
      cc = stages.sendtoCoordinates( s, coordinates )
      if cc == [ "out", "out", "out" ]:
       stages.close_socket( s )
       return cc
      filename = "scan2D_%s_x%s_y%s.bin" % ( args.subparser, str( center[ axes.index( "x" ) ] + i ), str( center[ axes.index( "y" ) ] + j ) )
      acquireData( tektronix, args.acquisition_number, args.average_number, filename )
  stages.close_socket( s )

def parseador():
  parser = argparse.ArgumentParser( description = "Laser Focus program" )
  subparser = parser.add_subparsers()
  first = subparser.add_parser( "First", help = "Focus on the First diode" )
  second = subparser.add_parser( "Second", help = "Focus on the Second diode" )
  third = subparser.add_parser( "Third", help = "Focus on the Third diode" )
  fourth = subparser.add_parser( "Fourth", help = "Focus on the Fourth diode" )
  fifth = subparser.add_parser( "Fifth", help = "Focus on the Fifth diode" )
  sixth = subparser.add_parser( "Sixth", help = "Focus on the Sixth diode" )
  seventh = subparser.add_parser( "Seventh", help = "Focus on the Seventh diode" )
  ref = subparser.add_parser( "Ref", help = "Focus on the Reference diode" )
  first.set_defaults( subparser = "First" )
  second.set_defaults( subparser = "Second" )
  third.set_defaults( subparser = "Third" )
  fourth.set_defaults( subparser = "Fourth" )
  fifth.set_defaults( subparser = "Fifth" )
  sixth.set_defaults( subparser = "Sixth" )
  seventh.set_defaults( subparser = "Seventh" )
  ref.set_defaults( subparser = "Ref" )
  parser.add_argument( "-f", "--files", nargs="+", help = "list of files to analyze", metavar = "" )
  parser.add_argument( "-a", "--acquisition_mode", type = str, choices = [ "sample", "peakdetect", "average", "envelope" ], default = "sample", help = "acquisition mode. Choices = sample, peakdetect, average, envelope. Default = %(default)s", metavar = "" )
  parser.add_argument( "-g", "--average_number", type = str, default = "4", help = "average number for average acquisition. Default = %(default)s", metavar = "" )
  parser.add_argument( "-n", "--acquisition_number", type = int, default = 100, help = "number of acquisitions for the TCT. Default = %(default)s. For average mode, default = 1", metavar = "" )
  parser.add_argument( "-c", "--channel", type = int, default = "1", help = "acquisition channel. Default = %(default)s", metavar = "" )
  parser.add_argument( "-v", "--voltage", type = str, default = "0", help = "bias voltage applied to the sensor in V. Default = %(default)s", metavar = ""  )
  parser.add_argument( "-m", "--compliance", type = float, default = "10e-6", help = "complienace. Default = %(default)s", metavar = "" )
  parser.add_argument( "-l", "--amp_voltage", type = str, default = "8", help = "bias voltage for the amplifier in V. Default = %(default)sV", metavar = ""  )
  parser.add_argument( "-j", "--amp_compliance", type = float, default = "300e-3", help = "compliance for the amplifier power supply. Default = %(default)sA", metavar = "" )
  parser.add_argument( "-t", "--temperature", type = str, default = "32", help = "acquisition temperature in F. Default = %(default)s", metavar = ""  )
  parser.add_argument( "-e", "--axis", type = list, default = "xyz", help = "focus the chosen axis. Default = [x,y,z]", metavar = "" )
  parser.add_argument( "-s", "--size", type = str, default = "Ref", choices = [ "Small", "Big", "Ref" ], help = "type of size for number of steps. Sizes = Small, Big, Ref. Default = %(default)s", metavar = ""  )
  parser.add_argument( "-b", "--bulk", type = str, choices = [ "p", "n" ], help = "bulk of the sensor. Choices = n, p", metavar = "" )
  parser.add_argument( "-x", "--no_turn_off", action='store_true', help = "do not turn off the power supply at the end." )
  parser.add_argument( "-y", "--no_turn_on", action='store_true', help = "do not control the HV power supply." )
  args = parser.parse_args()
  if args.voltage and not args.bulk and not args.go_to_position:
    parser.error( "--voltage requires --bulk" )
  if float( args.voltage  ) > 0 and args.bulk == "n":
    parser.error( "n bulk requires negative voltage" )
  if float( args.voltage  ) < 0 and args.bulk == "p":
    parser.error( "p bulk requires positive voltage" )
  if args.acquisition_mode == "average":
    args.acquisition_number = 1
  for ax in args.axis:
    if ax not in [ "x", "y", "z" ]:
      raise ValueError( "Humm... " + ax + " not standard axis. See help." )
    if args.axis.count( "x" ) > 1:
      for i in range( args.axis.count( "x" ) - 1 ):
        args.axis.remove( "x" )
    if args.axis.count( "y" ) > 1:
      for i in range( args.axis.count( "y" ) - 1 ):
        args.axis.remove( "y" )
    if args.axis.count( "z" ) > 1:
      for i in range( args.axis.count( "z" ) - 1 ):
        args.axis.remove( "z" )
  return args

def main( args ):
  factory = InterfaceFactory( "setupBrown.ini" )
  tektronix = factory.getDevice( "scope" )
  keithley = factory.getDevice( "highVoltage" )
  agilent = factory.getDevice( "lowVoltage" )
  shutil.copyfile( "sensors.txt", "sensors_back.txt" )
  agilent.setChannel( "P25V" )
  pW.setPowerSupply( agilent, args.amp_voltage, args.amp_compliance )
  if not args.no_turn_on:
    pW.setPowerSupply( keithley, args.voltage, args.compliance )
  tektronix.setChannel( args.channel )
  tektronix.acquireMode( args.acquisition_mode )
  if args.acquisition_mode == "average":
    tektronix.acquireAverageNumber( args.average_number )
  tektronix.singleSequence()
  sensors = cF.getCoordFromFile()
  s = stages.open_socket()
  stages.sendtoCoordinates( s, sensors[ args.subparser ] )
  getElectronicNoiseSignal( s, sensors, args, tektronix )
  stages.close_socket( s )
  findOptimumPosition( sensors, tektronix, args )
  if not args.no_turn_off:
    pW.turnOFFPowerSupply( keithley )


if __name__ == "__main__":
  args = parseador()
  main( args )
